### ISSUE TITLE
Advent Third Pickup +

### ISSUE THREAD

**Issue by VivaRado** [VivaRado/Advent#13]
Contours:

> Pickup of contour point positions as seen at [mjlagattuta/Advent-Pro
](https://github.com/mjlagattuta/Advent-Pro) for all applicable.

Scale:
 - Scale all glyphs by 100.28% to match original

Font Metadata:
 - As the current google font.

Kerning Classes:
 - Pending

Contour Fixes:
 - B - double point at exterior of crossbar.
 - C - point mid lower left stress.
 - Lslash - added L component.
 - OE - added O,E components.
 - P - Lower Bowl removed straight anchor point curve.
 - Psi - Top Right Ascender point non smooth.
 - Sigma - Top Stroke lighter on bold italic.
 - Theta - O component.
 - Thorn - Lower Bowl anchor to rounded.
 - U - Removed Bowl mid curve points.
 - a - Removed ascender mid curve points.
 - ae - added a,e components.
 - alpha - lower part of bowl smooth curve.
 - beta
 - c - Bowl mid curve cleanup.
 - f - ascender smooth point.
 - g
 - gamma - Descender straight point.
 - m - top right bowl smooth points.
 - mu - right finial straight point.
 - oe - added o,e components.
 - p - top bowl smooth, lower bowl meets stem straight.
 - q - bowl smooth.
 - r - ear smooth.
 - s - path removal.
 - germandbls - s finial path orientation.
 - tt - first t is decomposed to add spacing between letters second is component.
 - kappa - leg smoothing.
 - lambda - cleanup.
 - lslash - added l component.
 - gamma_gamma
 - lambda_lambda
 - gamma_kappa
 - sigma_tau - switched off.
 - sigma_chi - removed.

Classes:
Pending

**Comment by VivaRado** [comment]
Things already in since January 31 2019:

- removed duplicate glyphs,
- fixed metrics, 
- no interpolation issues, 
- fixed nameIDs and metadata (license file, copyright, etc.), 
- added instances, 
- and fixed designspace files (export weight and italics separately).

Things added now:

- added nbspace, 
- kerning from feature file is how I make the adjustments. fontmake takes that information if that information is available, so removing that extra instance of kerning from feature file is nogo.

**Comment by VivaRado** [comment]
Added italic.designspace

Total Designspaces:
 - weight - just weight no italics axis
 - italic - italics files only, and weight axis
 - weight_italic - italics and weight axis, all files

**Comment by VivaRado** [comment]
Starting with Classification:

A note before going forward, if a Left side Class is the Same as a Right side class.
The fontmake compiler joins them, so having those two classes in the groups PLIST doesn't really affect anything other than making the UFO lighter.

For me this is a requirement of the kerning adjustment interface as I target those groups explicitly, if one doesn't exist i don't assume it does, because it might exist with additional glyphs like in the case of O in Left side D. So the classes that have left and right being the same will remain like that in the sources. As after compile they get merged with no effect to the VF or OTF TTF.

And we start with:
```
{'GG': 4629, 'GL': 800, 'LG': 780, 'LL': 191}
```
Total Pairs 6400

**#!1** 
---
About AE in E:
```
<key>@MMK_L_E</key>
	<array>
		<string>AE</string>
		<string>E</string>
		<string>Eacute</string>
		<string>Ecaron</string>
		<string>Ecircumflex</string>
		<string>Edieresis</string>
		<string>Edotaccent</string>
		<string>Egrave</string>
		<string>Emacron</string>
		<string>Eogonek</string>
		<string>OE</string>
	</array>
```
If you do this then the class after compress becomes AE. making you lose all kerning that you have classified as E, because "A" in AE comes alphabetically first and the class gets renamed to AE.

**#!2**
---
```
<key>@MMK_L_H</key>
	<array>
		<string>H</string>
		<string>Hbar</string>
		<string>Hcircumflex</string>
		<string>I</string>
		<string>Iacute</string>
		<string>Icircumflex</string>
		<string>Idieresis</string>
		<string>Idotaccent</string>
		<string>Igrave</string>
		<string>Imacron</string>
		<string>Iogonek</string>
		<string>Itilde</string>
		<string>M</string>
		<string>N</string>
		<string>Nacute</string>
		<string>Ncaron</string>
		<string>Ncommaaccent</string>
		<string>Eng</string>
		<string>Ntilde</string>
	</array>
```
This class becomes renamed to Eng, losing all the classification you have for H. let alone all the rest of the letters.

**#!3**
---
```
<key>@MMK_L_J</key>
	<array>
		<string>J</string>
		<string>Jcircumflex</string>
		<string>Y</string>
		<string>Yacute</string>
		<string>Ycircumflex</string>
		<string>Ydieresis</string>
		<string>Ygrave</string>
	</array>
```
Including Y into J Left side class is a very good idea.
```
{'GG': 4568, 'GL': 787, 'LG': 780, 'LL': 235}
```
Total Pairs 6370 ~ 30 pairs reduction.
And the kerning passes rendering too!

**#!4**
---
```
<key>@MMK_L_Mu</key>
	<array>
		<string>Eta</string>
		<string>Mu</string>
		<string>Nu</string>
		<string>Pi</string>
		<string>Etatonos</string>
	</array>
```
This class gets renamed to Eta, my bad from previous classification, renamed to Eta, no big proglems as the letters are all "square".

**#!5**
---
```
	<key>@MMK_L_O</key>
	<array>
		<string>D</string>
		<string>Eth</string>
		<string>Dcaron</string>
		<string>Dcroat</string>
		<string>O</string>
		<string>Oacute</string>
		<string>Ocircumflex</string>
		<string>Odieresis</string>
		<string>Ograve</string>
		<string>Ohungarumlaut</string>
		<string>Omacron</string>
		<string>Oslash</string>
		<string>Otilde</string>
		<string>Q</string>
	</array>
```
This class will be renamed to D, but it's not a bad idea, I'm testing it, by removing Left side O class, and adding it's contents into class D.
```
{'GG': 4507, 'GL': 773, 'LG': 720, 'LL': 166}
```
Total Pairs 6166 ~ 100 pairs reduction.
Passes rendering too!

**#!6**
---
Adding dollar into S.
I have noticed it break kerning in smallcase letters.

**#!7**
---
adding yen to a Capital letter class doesn't break though, so ... go figure... )

**#!8**
---
ae and oe in e
```
	<key>@MMK_L_e</key>
	<array>
		<string>ae</string>
		<string>e</string>
		<string>eacute</string>
		<string>ecaron</string>
		<string>ecircumflex</string>
		<string>edieresis</string>
		<string>edotaccent</string>
		<string>egrave</string>
		<string>emacron</string>
		<string>eogonek</string>
		<string>oe</string>
	</array>
```
This class would be renamed to ae, losing kerning for all e.

**#!9**
---
i and dotlessi
```
	<key>@MMK_L_i</key>
	<array>
		<string>i</string>
		<string>dotlessi</string>
		<string>iacute</string>
		<string>icircumflex</string>
		<string>idieresis</string>
		<string>igrave</string>
		<string>imacron</string>
		<string>iogonek</string>
		<string>itilde</string>
		<string>u</string>
		<string>uacute</string>
		<string>ubreve</string>
		<string>ucircumflex</string>
		<string>udieresis</string>
		<string>ugrave</string>
		<string>uhungarumlaut</string>
		<string>umacron</string>
		<string>uogonek</string>
		<string>uring</string>
		<string>utilde</string>
	</array>
```
This class would be renamed into dotlessi and u and i would lose kerning.
In fact any dotless in a class has the class renamed to dotless because alphabetically "d"
and there is loss of kerning. Unless is passed into a grek class... go figure...

**#!10**
---
l in left side d
```
<key>@MMK_L_l</key>
	<array>
		<string>d</string>
		<string>eth</string>
		<string>dcaron</string>
		<string>dcroat</string>
		<string>l</string>
		<string>lacute</string>
		<string>lcaron</string>
		<string>lcommaaccent</string>
		<string>ldot</string>
		<string>lslash</string>
	</array>
```
This class would be renamed "d", but the idea of putting l inside d left side class is not bad.
```
{'GG': 4446, 'GL': 760, 'LG': 720, 'LL': 166}
```
Total Pairs 6092 ~ 100 pairs reduction.
And renders ok!

**#!11**
---
m and a in one class
```
<key>@MMK_L_m</key>
	<array>
		<string>a</string>
		<string>aacute</string>
		<string>abreve</string>
		<string>acircumflex</string>
		<string>adieresis</string>
		<string>agrave</string>
		<string>amacron</string>
		<string>aogonek</string>
		<string>aring</string>
		<string>atilde</string>
		<string>m</string>
		<string>n</string>
		<string>nacute</string>
		<string>ncaron</string>
		<string>ncommaaccent</string>
		<string>ntilde</string>
	</array>
```
This class gets renamed to "a" and the rest of the letters lose kerning.

**#!12**
---
Right side D to include O like in #!5 
Good idea.
RESULTS:
```
{'GG': 4391, 'GL': 760, 'LG': 708, 'LL': 166}
```
Total Pairs 6025 ~ 50 pairs reduction.

**#!13**
---
removing right class "o" and "e" and adding all contents to "c" for right side... right "ceo" class.... (business organization humor here...) Unfortunately even if this sounds cool it affects kerning to the left side classes of the participants. Read further on as i test them. this results to those 200 pairs being added back.
```
{'GG': 4281, 'GL': 760, 'LG': 684, 'LL': 166}
```
Total Pairs 5891 ~ 200 pairs reduction.

**#!14**
---
added grek ligatures into appropriate classes (gamma_gamma, gamma_kappa, lambda_lambda)

**#!15**
---
added grek Sigma in right side Chi, removed it from right side Epsilon for successfully kerning "ΟΣ", Removed Xi from Chi, to create a new class Xi and added left side Sigma as those letters look the same from the right side. ~ 50 pairs reduction.

Testing:
---
Testing all [Kerning Pair Details permuted pairs](https://github.com/VivaRado/Advent/blob/master/docs/kerning_adjustments/kerning_pair_details) for kerning loss.

During this process i have decided to deprecate the Class Based permutation testing. And opted for a more complete Letter Based permutation as a lot of combinations are not present in the Class Based.

**Letter Based Permutations (LB)**:
 - **Latin VS Latin Capitals Letter Based Permutation (LBLCLC)**:
   - **set A**: ok
   - **set B**: ok
 - **Latin VS Latin SmallCase Letter Based Permutation (LBLSLS)**:
   - **set A**: "ceo" right class "c" with "e" inside influences left side "e" class. + 100 pairs as reinstated right side "e". (strange that if you have a right side letter in a different parent class it affects the left side class.). Discovered while kerning "ej", testing for "oj" - and yes the same happens here. + 100 pairs as i reinstated right side "o" aswell. - That is not because of the "j" class rather because of adding "e" and "o" in the "c" right side class - it affects left side "e" and "o" to lose kerning.
   - **set B**: ok
 - **Latin Capitals VS Latin SmallCase Letter Based Permutation (LBLCLS)**
   - **set A**: ok
   - **set B**: ok
 - **Greek VS Greek Capitals Letter Based Permutation (LBGCGC)**:
   - **set A**: - im very glad to say this is ok aswell as latin classes affect grek sometimes, plus with that Xi and Sigma shenanigans... it could have failed.
   - **set B**: ok
 - **Greek VS Greek SmallCase Letter Based Permutation (LBGSGS)**:
   - **set A**: ok
   - **set B**: ok
   - **set C**: ok 
 - **Greek Capitals VS Greek SmallCase Letter Based Permutation (LBGCGS)**:
   - **set A**: ok
   - **set B**: ok

Results:
---
```{'GG': 4458, 'GL': 761, 'LG': 708, 'LL': 166}```

Total Pairs: ```6093```

Total pair reduction: ```~ 307```

**Comment by davelab6** [comment]
Great stuff!

**Comment by davelab6** [comment]
What remains to close this issue?

**Comment by VivaRado** [comment]
Hello Dave, i think its good to go, let me close that.
