### ISSUE TITLE
Incompatible glyphs

### ISSUE THREAD

**Issue by m4rc1e** [VivaRado/Advent#20]
Fontmake reports that the following glyphs are incompatible when generating a VF for adv_wght_wdth_ital.designspace

```
fontmake.errors.FontmakeError: In 'adv_wght_wdth_ital.designspace': Generating fonts from Designspace failed: fonts contains incompatible glyphs: 
'Gcommaaccent', 
'Kcommaaccent', 
'Lcommaaccent', 
'Ncommaaccent', 
'Omegatonos', 
'Rcommaaccent', 
'Scommaaccent', 
'Tcedilla', 
'V_alt', 
'gcommaaccent', 
'jcircumflex', 
'kcommaaccent', 
'lcommaaccent', 
'mugreek', 
'ncommaaccent',
'rcommaaccent', 
'scommaaccent', 
'tcedilla'
```

**Comment by m4rc1e** [comment]
Will be fixed in #21

**Comment by VivaRado** [comment]
Try now, they where old UFOs. Now synced with my local.

**Comment by m4rc1e** [comment]
@VivaRado Have the updated ufos also fixed the missing glyphs reported in https://github.com/VivaRado/Advent/pull/21#issue-1105741479?

**Comment by VivaRado** [comment]
Yes, also compiling with /font_source/compile_latest_variable_flavors.sh 
returns the VAR for all designspace OK

**Comment by VivaRado** [comment]
As for EFO, if you could just ignore it on the pull, I still need it on this repo.
