### ISSUE TITLE
Messy Outlines

### ISSUE THREAD

**Issue by VivaRado** [VivaRado/Advent#4]
Many outlines are somewhat messy, offcurve points on straight segments, 0-length handles, points near but not on extremes, and some odd forms like the joining of the two curved strokes in /B

**Comment by VivaRado** [comment]
Fixed some issues I could identify like the aforementioned "B" problem and a few more letters like "G,C". I will go over the paths again and report fixes on each letter.

**Comment by mjlagattuta** [comment]
I think it would be good to look at the /S, /s,  and take a look at all the latin lowercase letters. Even though some of them look fine, they may have non-orthogonal handles on what appear to be extremes.

**Comment by VivaRado** [comment]
- bld: 
  - Q : Thinner Tail
  - Oslash : Thinner Slash, Shorter Slash
  - oslash : Thinner Slash, Shorter Slash
  - A : Higher Negative Apex
  - Lambda : Higher Negative Apex
  - Hbar : Thinner Crossbar
  - hbar : Thinner Crossbar
  - K : Lighter Negative Apex, Aperture
  - N : Lighter Negative Apex, Aperture
  - M : Lighter Negative Apex, Aperture
  - dollar : Thinner Slash
  - cent : Thinner Slash
  - slash : Thinner
  - percent : Thinner Slash
  - G : Balanced Spur
  - R : Balanced Leg

- bld_it: 
  - Q : Thinner Tail
  - Oslash : Thinner Slash, Shorter Slash
  - oslash : Thinner Slash, Shorter Slash
  - A : Higher Negative Apex
  - Lambda : Higher Negative Apex
  - Hbar : Thinner Crossbar
  - hbar : Thinner Crossbar
  - K : Lighter Negative Apex, Aperture
  - N : Lighter Negative Apex, Aperture
  - M : Lighter Negative Apex, Aperture
  - W : Lighter Negative Apex, Aperture
  - X : Negative Apex, Aperture Alignement
  - ampersand : minor
  - dollar : Thinner Slash
  - cent : Thinner Slash
  - beta : minor
  - slash : Thinner
  - percent : Thinner Slash
  - G : Balanced Spur
  - R : Balanced Leg

- reg: 
  - Oslash : Shorter Slash
  - oslash : Shorter Slash
  - G : Balanced Spur
  - R : Balanced Leg

- reg_it: 
  - Oslash : Shorter Slash
  - oslash : Shorter Slash
  - dollar : More Slanted Slash
  - G : Balanced Spur
  - R : Balanced Leg

- thn: 
  - G : Balanced Spur
  - R : Balanced Leg

- thn_it: 
  - G : Balanced Spur
  - R : Balanced Leg
