### ISSUE TITLE
Accent Anchors

### ISSUE THREAD

**Issue by VivaRado** [VivaRado/Advent#7]
Please inform of letter and weight, with misalignment if it happens and you notice.
Thank you!

**Comment by VivaRado** [comment]
Aring / reg_it

**Comment by VivaRado** [comment]
For the italics, there needs to be an additional Xoffset.

**Comment by mjlagattuta** [comment]
Some notes on missing and missaligned anchors for the Latin glyphs. The list is for capitals but most of these correspond to their lowercase counterparts:
- /D needs "bottom" and "center" anchors
- /B, /F, /AE, /OE, /V, /Chi need "top" and "bottom" anchors
- /A, /E, /I /U /O need "bottom" anchor and the "ogonek" anchor should not be centered for /E or /A
- /O needs an "ogonek" anchor and could use a "center" anchor
- /H gets "top" and "tonos" from /Eta but could use "bottom" and "center"
- /J needs "bottom" anchor
- /K needs "top" anchor
- /L could use "center" anchor
- /M, and /P need "bottom" and "top"
- /Q needs "bottom" (takes "top" from /O)
- /T could use "center" anchor
- /W, /Y, and /Z need "bottom" anchors

**Comment by VivaRado** [comment]
Took some time to answer cause had to crosscheck Unicode and advents glyphlist.
Some of the anchor requests could happen but they are related to glyphlist extension.
Also please check without autoallign in glyphs app because the components have been aligned by offset during the component placement. The anchor might be center but the positioning is according to coordinates of given anchor and Xoffset - Aogonek for example the anchor is at the middle but I provide X and Yoffset and position it accordingly. I don't know why we need a center-anchor if not for Ldot or ldot - which I just offset from the top anchor.

- **/D**:
  - for the center : if it is for Eth - that is E+D - but I can just leave the "-" bar of E and add it into componets so it replaces just the "D" part.
  - for the bottom D has no ogonek or any bottom accent. I don't see why it needs anything than top.
- **/B**:
  - B does get accented:
    - U+1E04 - B with Dot Below
    - U+1E06 - B with Line Below
- **/F**:
  - F does get accented: 
    - U+1E1E - Latin Capital Letter F with Dot Above
- **/AE**: 
  - AE could get a top for acute and macron:
    - U+01E2 - Ǣ - Latin Capital Letter Ae with Macron, 
    - U+01FC - Ǽ - Latin Capital Letter Ae with Acute
- **/OE**: 
  - OE Doesn't get accented I think, at least according to quick Unicode check.
- **/V**: 
  - V does get accented:
    - U+1E7C - Ṽ - Latin Capital Letter V with Tilde
    - U+1E7E - Ṿ - Latin Capital Letter V with Dot Below
- **/Chi**: 
  - Chi Doesn't get accented either.
- **/O**: 
  - O Doesn't get accented at the center.
  - as for U+01EA - Ǫ - Latin Capital Letter O with Ogonek, we can add an ogonek anchor, but we also need to add it to the glist.
- **/J**: 
  - J gets only top accents according to Unicode check.
- **/K**: 
  - K top accent, not in glist, but we could it if we added glyphs:
    - U+01E8 - Ǩ - Latin Capital Letter K with Caron
    - U+1E30 - Ḱ - Latin Capital Letter K with Acute
  - if it is to add letters to the glyphlist for K bottom accent we could also add:
    - U+0136 - Ķ - Latin Capital Letter K with Cedilla
    - U+1E32 - Ḳ - Latin Capital Letter K with Dot Below
    - U+1E34 - Ḵ - Latin Capital Letter K with Line Below
- **/L**: 
  - L could get a center instead of offsetting it from top.
- **/M**: 
  - M for top could yes - update the glist as well:
    - U+1E3E - Ḿ - Latin Capital Letter M with Acute
    - U+1E40 - Ṁ - Latin Capital Letter M with Dot Above
  - M for bottom (glist update):
    - U+1E42 - Ṃ - Latin Capital Letter M with Dot Below
- **/Q**: 
  - Q for bottom could yes - but the tail is in Q glyph as static contour and the Comp script just replaces the O - I don't see a reason for a component there - same as Eth that I need to fix:
- **/T**: 
  - T for center could yes - but we could use the same logic as for Eth and Q.
- **/W**: 
  - W for bottom:
    - U+1E88 - Ẉ - Latin Capital Letter W with Dot Below (glist update)
- **/Y**: 
  - Y for bottom:
    - If it is for yen, then same as Tbar, Eth, Q - (component the letter - and static otherwise unique contour - no need for component)
- **/Z**: 
  - Z for bottom (glist update):
    - U+1E92 - Ẓ - Latin Capital Letter Z with Dot Below
    - U+1E94 - Ẕ - Latin Capital Letter Z with Line Below

Glyphlist update and anchor additions for later glyphlist update:

    - U+1E04 - B with Dot Below (add bottom anchor)
    - U+1E06 - B with Line Below (add bottom anchor)
    - U+1E1E - Latin Capital Letter F with Dot Above (add top anchor)
    - U+01E2 - Ǣ - Latin Capital Letter Ae with Macron (add top anchor)
    - U+01FC - Ǽ - Latin Capital Letter Ae with Acute (add top anchor)
    - U+1E7C - Ṽ - Latin Capital Letter V with Tilde (add top anchor)
    - U+1E7E - Ṿ - Latin Capital Letter V with Dot Below (add bottom anchor)
    - U+01EA - Ǫ - Latin Capital Letter O with Ogonek (add ogonek anchor)
    - U+01E8 - Ǩ - Latin Capital Letter K with Caron (add top anchor)
    - U+1E30 - Ḱ - Latin Capital Letter K with Acute (add top anchor)
    - U+0136 - Ķ - Latin Capital Letter K with Cedilla (add bottom anchor)
    - U+1E32 - Ḳ - Latin Capital Letter K with Dot Below (add bottom anchor)
    - U+1E34 - Ḵ - Latin Capital Letter K with Line Below (add bottom anchor)
    - U+1E3E - Ḿ - Latin Capital Letter M with Acute (add top anchor)
    - U+1E40 - Ṁ - Latin Capital Letter M with Dot Above (add top anchor)
    - U+1E42 - Ṃ - Latin Capital Letter M with Dot Below (add bottom anchor)
    - U+1E88 - Ẉ - Latin Capital Letter W with Dot Below (add bottom anchor)
    - U+1E92 - Ẓ - Latin Capital Letter Z with Dot Below (add bottom anchor)
    - U+1E94 - Ẕ - Latin Capital Letter Z with Line Below (add bottom anchor)

Component Updates:
- Ldot and ldont (add center anchor) or just ofset from top I guess.
- Tbar, Eth, Q and other letters with unique occurrences of contour not needed to be componentized, have the base replacement of T, D, O - the base letter for each occasion - and the unique contour - just remains in the glyph uncomponentized.

Thank you Mike for your suggestions - especially bringing to my attention the extension of the glyphlist.
The anchors so far are distributed as suggested by you before, according to need to exist basis. If we have some letter that requires it the anchor will be added.

**Comment by mjlagattuta** [comment]
I was not necessarily suggesting that you update the glyph set; having the extra anchor information is good even if there is not a composite in the font using it. Some apps can construct these composites on the fly based on the anchor information, so presumably you could get an /M with /cedillacomb in InDesign. Obviously some combinations will not be used but others may be utilized by end users.

I’m not sure it is a good idea to position the components as an offset from the anchors. That somewhat defeats their purpose, ideally the offset should be 0 and I think it can be 0 based on Advent’s design. If this is the case then auto-align in Glyphs App should not be a problem except for composites that absolutely require an offset from an anchor.

As an example of a potential problem with offsetting from anchors, if you are typing in a piece of software that allows combining marks to attach to anchors on the fly then those marks will not align with the other marks, since the composite marks are offset and the non-standard one’s will instead snap to anchors.

The /D /O /L and /T can take center anchors so that you can attach/strokeshortcomb  /slashlongcomb /slashshortcomb and /strokeshortcomb, the same applies to their lowercase counterparts. I believe it is fine to build the composites with just a component and an outline, but in cases where a form may be reused like in the upper and lower /Lslash or the upper and lower /Tbar then it may be better to add the combining glyphs and the center anchor :)

**Comment by VivaRado** [comment]
Hello Mike, so here's another one about anchors.

> Missing anchor. According to the opentype spec, if a glyph contains an anchor point for one anchor class in a subtable, it must contain anchor points for all anchor classes in the subtable. Even it*if, logically, they do not apply and are unnecessary. 

[ ~ Font Validation window ](https://fontforge.github.io/en-US/documentation/interface/validation/)

Does that mean that there is no "need to exist basis" and all anchors have to be in all letters no matter what, I think it does. 

If so I will have to revert the code to when the componentization applies all anchors to the glyphs.

**Comment by mjlagattuta** [comment]
I think this has less to do with the way you set up your source file and more with the way the final binary is built, meaning I believe fontmake handles this and there is no need to add all anchors for each glyph in your source; some glyphs don't make sense to have a "center" anchor, or "ogonek" anchor, etc.

**Comment by VivaRado** [comment]
As seen in the TTX, quick check, there is no anchoring information, thus there is no actual size reduction if all the anchors exist in the UFO. But as for standards I think the source files should include them. I will see at some point to add a include_all = True to the accent_logic function. Let alone we escape the future problems of adding anchors in case we add glyphs.

**Comment by VivaRado** [comment]
Accent Component Alignments:
 - bld_it:

   ``` 
   iotatonos, itilde, jcircumflex, lcaron, zdotaccent, Ldot, ldot, wgrave
   ```
 - bld:

   ``` 
   iotatonos, itilde, jcircumflex, lcaron, zdotaccent, Ldot, ldot, wgrave
   ```
 - reg:

   ``` 
   wgrave, jcircumflex, iotatonos, itilde, lcaron
   ```
 - reg_it: 

   ```
   racute, rcommaaccent
   ```
 - thn: 

   ```
   wgrave
   ```
 - thn_it: 

   ```
   Aring, aring, Aacute,
   ```

**Comment by mjlagattuta** [comment]
What do you mean by no anchoring information? There should be MarkToBase and MarkToMark subtables within the GPOS table

Also what is the list of glyphs above: "Accent Component Alignments" ?

**Comment by VivaRado** [comment]
Its just what accent components got fixed. I ll check again a TTX.

**Comment by VivaRado** [comment]
All anchors have been aligned, the UFOs do not include anchor information, that is only if someone exports from the source, as i find it reasonable to not burden the already aligned UFOs with anchor kb. If anyone is interested in developing or adding glyphs or accents i think that they will have to deal with the EFO, it is fairly easy to export UFOs with anchors from the EFO just with efo_to_ufo.py.
